AG-54864 Increase default MTU to 1350 to avoid QUIC fragmentation problem (#34)
* Fix missing package for devcontainer

* Fix error on gcc

error: enumerated and non-enumerated type in conditional expression

* Change default MTU size to 1350

* Update changelog

* Fix case

Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>

---------

Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>